// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhOITuwItE0c_YYsfq6bMriQuqqWJa2S0',
    appId: '1:895800313585:web:27f15cd868b5fe697b4b50',
    messagingSenderId: '895800313585',
    projectId: 'readio-7e0ed',
    authDomain: 'readio-7e0ed.firebaseapp.com',
    databaseURL: 'https://readio-7e0ed-default-rtdb.firebaseio.com',
    storageBucket: 'readio-7e0ed.appspot.com',
    measurementId: 'G-R174E5N6TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnezLf5JLi--a_V_e1xsfkqig3GoDEYMM',
    appId: '1:895800313585:android:d237098e641fe3377b4b50',
    messagingSenderId: '895800313585',
    projectId: 'readio-7e0ed',
    databaseURL: 'https://readio-7e0ed-default-rtdb.firebaseio.com',
    storageBucket: 'readio-7e0ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUpGEBTXylZhMl2s45TnJzUYmBFJCMcho',
    appId: '1:895800313585:ios:e55ae26a9c7927797b4b50',
    messagingSenderId: '895800313585',
    projectId: 'readio-7e0ed',
    databaseURL: 'https://readio-7e0ed-default-rtdb.firebaseio.com',
    storageBucket: 'readio-7e0ed.appspot.com',
    iosBundleId: 'com.example.masterMind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhOITuwItE0c_YYsfq6bMriQuqqWJa2S0',
    appId: '1:895800313585:web:b5ab33f3927132d77b4b50',
    messagingSenderId: '895800313585',
    projectId: 'readio-7e0ed',
    authDomain: 'readio-7e0ed.firebaseapp.com',
    databaseURL: 'https://readio-7e0ed-default-rtdb.firebaseio.com',
    storageBucket: 'readio-7e0ed.appspot.com',
    measurementId: 'G-86NLKJ6P0Z',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUpGEBTXylZhMl2s45TnJzUYmBFJCMcho',
    appId: '1:895800313585:ios:e55ae26a9c7927797b4b50',
    messagingSenderId: '895800313585',
    projectId: 'readio-7e0ed',
    databaseURL: 'https://readio-7e0ed-default-rtdb.firebaseio.com',
    storageBucket: 'readio-7e0ed.appspot.com',
    iosBundleId: 'com.example.masterMind',
  );

}