// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhvBPDv5I73uObRrcK_mEz5zdcmvZEQg0',
    appId: '1:547451365319:web:116382adbee631073e9be2',
    messagingSenderId: '547451365319',
    projectId: 'readio-mm',
    authDomain: 'readio-mm.firebaseapp.com',
    storageBucket: 'readio-mm.appspot.com',
    measurementId: 'G-GJQZ8VJ7HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwCcv0zCyzJYo3UMstYyVfSwCYckcn_0s',
    appId: '1:547451365319:android:f6588b7f24a0cbac3e9be2',
    messagingSenderId: '547451365319',
    projectId: 'readio-mm',
    storageBucket: 'readio-mm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy31eCjuNgeqg2W_yBE2vlADtf95TAjVg',
    appId: '1:547451365319:ios:526ee472a2a4b9493e9be2',
    messagingSenderId: '547451365319',
    projectId: 'readio-mm',
    storageBucket: 'readio-mm.appspot.com',
    iosBundleId: 'com.example.masterMind',
  );
}
